### ISSUE TITLE
Missing from Imperial update

### ISSUE THREAD

**Issue by Michalx11** [secretcowlevel/DoomtrooperPublic#124]
There are few things missing from Imperial update:

Reassigment - Remove RESTRICTED keyword and add "all attachmets are shuffled back with warrior"

Paladines Favor - Remove RESTRICTED keyword (to be able to have 3 copies in play)

Edward S Murdoch - change his stats to 4/7/7/7 and remove SLAYER (to focus Golden Lions more on S with guns and Clansmens on F  with Blades)

The Shillelagh - add +2F

Assasilant - 1 action +2S and opponent's Armor is disabled during S combat (same as Lucky Shot)

**Comment by david-roxygen** [comment]
yeah, I confirm all :-D

**Comment by framerate** [comment]
mostly a dupe of #126 

Shillelagh looks fine but needed a text update (fixed), assailant was purposefully held back due to code complexity but I'll add another bug
