### ISSUE TITLE
3 missing important updates

### ISSUE THREAD

**Issue by david-roxygen** [secretcowlevel/DoomtrooperPublic#126]
**Reassignment (IMPERIAL) [C]**
ANNIHILATED
Play on a Warrior as 1 Tactical Action. The Warrior and all ATTACHMENT cards (owned) are shuffled
into its owner's draw pile. The owner regains the Warrior's [V] in [DP].
notes: not restricted; the attachments should be reshuffled together with the warrior

**Edward S. Murdoch (IMPERIAL) [R]**
UNIQUE, GOLDENLION
You require one fewer Action to play FIREARMS cards (minimum 0) on GOLDENLION warriors.
1 Action: search through your draw pile and put any one FIREARM card into your hand.
F: 4S: 7 A: 7 V: 7
notes: F and S switched; SLAYER and POWER IMMUNITY REMOVED (new golden lions should be focused on S combat)

**Paladine's Favor (IMPERIAL) [U]**
INFLUENCE
While Imperial warriors are in your squad, your maximum hand size increases by +1
notes: not restricted; the effect of multiple copies should stack

**Comment by framerate** [comment]
updated REASSIGNMENT keywords and made new code to return attachments to owner deck (seems to work but needs testing!)

updated EDWARD keywords and stats

PALADINE - removed RESTRICTED keyword
