### ISSUE TITLE
BOUNTY on Interceptor doesnt work

### ISSUE THREAD

**Issue by Michalx11** [secretcowlevel/DoomtrooperPublic#127]
Opponnents V is supposed to increase by 1

**Comment by framerate** [comment]
Note: this DID add it, but only during combat. I presume it was turning off. I'm going to make it perm, but we'll see what bugs that causes haha

**Comment by Michalx11** [comment]
During my tests opponnent's V never increased during combat Nor was the reward for killing such warrior increased by 1. So if it DID in fact increased then it must have dissaoered at `end.combat` and never add to reward for killing such warrior.
I worry that by making it permanent it will increase opponnents V even after your wsrrior fails to kill him/her
